name: Lint and validate OpenAPI specs
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v3
      - name: Run OpenAPI Lint Action
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: openapi/workflow_execution_service.openapi.yaml
  diff:
    name: Show OpenAPI differences relative to target branch
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Check out head branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: head
      - name: Check out base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base
      - name: Run OpenAPI Diff Action
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/openapi/workflow_execution_service.openapi.yaml
          base-spec: base/openapi/workflow_execution_service.openapi.yaml

  validate:
    name: Validate OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v3
      - name: Run OpenAPI Validate Action
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/workflow_execution_service.openapi.yaml
